apiVersion: v1
kind: Pod
metadata:
  name: welcome-bot
  labels:
    name: welcome-bot
spec:
  containers:
  - name: welcome-bot
    image: welcome-bot
    imagePullPolicy: Never
    ports:
      - containerPort: 8080
        name: http-web-svc
        
---
apiVersion: v1
kind: Service
metadata:
  name: welcome-bot-svc
spec:
  selector:
    name: welcome-bot
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 8080
    targetPort: http-web-svc