---
 - name: Build quiz-bot
   hosts: localhost

   tasks:
   - name: Build welcome-bot
     docker_image:
      build:
        path: ../welcome-bot
        dockerfile: Dockerfile
      name: welcome-bot
      source: build
      state: present

   - name: Build worker-bot
     docker_image:
      build:
        path: ../worker-bot
        dockerfile: Dockerfile
      name: worker-bot
      source: build
      state: present

   - name: Run welcome-bot
     docker_container:
      name: welcome-bot
      image: welcome-bot
      ports: 
      - "80:80"
      volumes:
      - ../utils:/root


