---
 - name: Build quiz-bot
   hosts: localhost

   tasks:
   - name: Build welcome-bot
     docker_image:
      build:
        path: /home/ubuntu/chat-bot/welcome-bot
        dockerfile: Dockerfile
      name: quiz-bot
      source: build
      state: present
