---
 - name: Build quiz-bot
   hosts: localhost

   tasks:
   - name: Build welcome-bot
     community.docker.docker_image:
      name: welcome-bot:latest
      build:
        path: ../welcome-bot/
        dockerfile: Dockerfile
      source: build
      state: present